#!/usr/bin/env python3
"""Materializes final_artifact/element-<bug>/ for every bug in manifest_android.py.

Run from anywhere; paths are resolved relative to this file. Safe to re-run (idempotent,
overwrites generated files but never touches ../bm_instrument). Does not manage `plans/` or
`experimental_results/` content — populate `plans/round<N>/` and `apk/` yourself; this only ever
checks whether the expected APK is already there.
"""
import os
import stat
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

sys.path.insert(0, HERE)
from manifest_android import BUGS, UNPACKAGEABLE  # noqa: E402

RUN_EXPERIMENT_TMPL = """\
#!/bin/bash
# Element {branch} — {title}
# Auto-generated by ../generate_android.py from ../manifest_android.py.
#
# THE single command to reproduce this bug (needs a connected arm64-v8a device/emulator with
# USB debugging enabled, reachable via `adb devices`):
#   ./run_experiment.sh
#
# What it does: installs this bug's pre-built APK, captures a baseline log, then for each round
# in [{rounds}] offline-patches the target class(es) via dex2jar+CommandLine (matching the actual
# production pipeline this corpus's results were captured with), attempts to build+attach a live
# JVMTI agent for that round (falls back to a documented no-op if $ANDROID_NDK isn't set — see
# ../ANDROID_README.md), drives the UI, and collects logcat. Results land in ./results/.
set -euo pipefail
cd "$(dirname "$0")"

if [ ! -f apk/vector-gplay-arm64-v8a-debug.apk ]; then
    echo "[MISSING] apk/vector-gplay-arm64-v8a-debug.apk — see ../ANDROID_README.md" >&2
    exit 42
fi
if ! adb devices | grep -qw device; then
    echo "No adb device attached (adb devices shows none in 'device' state)." >&2
    echo "Connect a real arm64-v8a device or emulator with USB debugging enabled and retry." >&2
    exit 43
fi

mkdir -p results
PACKAGE="{package}"

echo "== installing {folder}'s APK =="
adb uninstall "$PACKAGE" >/dev/null 2>&1 || true
adb install -r apk/vector-gplay-arm64-v8a-debug.apk

echo "== launch the app manually now, sign in, and open a room, then press Enter to continue =="
read -r -p "press Enter once the app is open and ready: " _

echo "== baseline capture =="
bash /opt/lib/drive_ui.sh &
DRIVE_PID=$!
bash /opt/lib/collect_log.sh results/baseline.log 40
wait $DRIVE_PID 2>/dev/null || true

for round in {rounds}; do
    echo "== round r$round: offline dex2jar+CommandLine patch =="
    python3 /opt/lib/patch_round.py --apk apk/vector-gplay-arm64-v8a-debug.apk \\
        --plan "plans/round${{round}}" --workdir "work/round${{round}}"

    echo "== round r$round: attempting live JVMTI agent build (needs \\$ANDROID_NDK) =="
    python3 /opt/lib/properties_to_btm.py "plans/round${{round}}" "work/round${{round}}/round.btm"
    bash /opt/lib/build_agent.sh "work/round${{round}}/round.btm" "work/round${{round}}/agent"

    PID=$(adb shell pidof "$PACKAGE" | tr -d '\\r')
    if [ -n "$PID" ]; then
        adb push "work/round${{round}}/agent/libagent.so" /data/local/tmp/
        adb shell run-as "$PACKAGE" cp /data/local/tmp/libagent.so ./libagent.so || true
        adb shell cmd activity attach-agent "$PID" "/data/user/0/$PACKAGE/libagent.so" || \\
            echo "attach-agent failed — see ../ANDROID_README.md's live-attach caveat" >&2
    fi

    bash /opt/lib/drive_ui.sh &
    DRIVE_PID=$!
    bash /opt/lib/collect_log.sh "results/round${{round}}.log" 40
    wait $DRIVE_PID 2>/dev/null || true
done

echo "== done. Results in ./results/, offline-patched classes in ./work/ =="
"""

README_TMPL = """\
# Element {branch} — {title}

Auto-generated by `../generate_android.py` from `../manifest_android.py`. Do not hand-edit
`run_experiment.sh`; edit the manifest and regenerate (`python3 ../generate_android.py`).

## Reproduce

Needs a connected arm64-v8a Android device or emulator with USB debugging on:

```bash
./run_experiment.sh
```

## Version / provenance

| | |
|---|---|
| Element version | `{element_version}` |
| Exact commit | `{commit}` |
| `element-android` branch | `{branch}` (also in `element-android2`) |
| Package | `{package}` |
| Symptom probe | `{symptom_class}.{symptom_method}` |
| Rounds | {rounds} |

Full commit provenance (root-cause commit(s) reverted, instrumentation commit(s)) is in
`../../bm_instrument/README.md`'s per-bug table and `../../bm_instrument/ARTIFACT_EVALUATION.md` §4.1.

## What's in this folder

- `apk/vector-gplay-arm64-v8a-debug.apk` — the actual pre-built, working APK this bug was captured
  against. Not included here; fetch it yourself (see `../ANDROID_README.md`) and place it at this
  path.
- `plans/round1/`, `plans/round2/`, ... — this bug's instrumentation plans, as
  `round<N>/<id>.properties[.disabled]` — same layout the server-side bugs use (see
  `final_artifact/README.md`'s "Instrumentation plan layout"). `plans/symptom.properties` (top
  level) is the final, confirmed probe.
- `results/` — populated by `run_experiment.sh` on a fresh run.
{notes_section}
## How `run_experiment.sh` reproduces each round

1. **Offline dex2jar+CommandLine patch** (`android-common/lib/patch_round.py`, adapted from the
   actual production script `bm_instrument8/run.py`): unpacks the APK, decompiles the dex
   containing each round's target class via vendored `dex2jar`, splices in the logging bytecode
   via `ca.uoft.drsg.bminstrument.CommandLine` (the **Android-branch** build of the instrumentation
   tool — see `../ANDROID_README.md` for why this isn't `bm_instrument/main`'s jar), and produces a
   patched `.dex` per changed class under `work/round<N>/out/`.
2. **Live attach** (`android-common/lib/build_agent.sh` + `adb shell cmd activity attach-agent`):
   attempts to hot-load the patched class into the *already-running* app process without a
   reinstall, matching the original pipeline's technique. This step needs a JVMTI agent rebuilt
   per round (different target class each time) — **requires `$ANDROID_NDK`**; without it, this
   step is skipped with a warning and only the offline-patched `.dex` (step 1) is produced for
   inspection. See `../ANDROID_README.md`'s "Known gap" section — this is the one part of the
   original pipeline that could not be verified byte-for-byte against this checkout's available
   source.
3. **Drive UI + collect** (`android-common/lib/drive_ui.sh` / `collect_log.sh`): taps through
   Element's compose/send flow and greps logcat for `DEADBEEF`/`CLODS`/`[Agent]`/`[BM]` markers.

## Mapping to the results table

- **Det?/Succ?** — grep a fresh `results/round<N>.log` for `DEADBEEF`/`CLODS` matching the
  symptom probe above.
- **#Iter** = {n_rounds} (rounds {rounds}).
- **#SI** = count of `.properties` files under `plans/round<N>/` (excluding `.disabled`), summed
  across rounds.
- **lat.(ms)** — diff `DEADBEEF: START <op> = <ts>` / `END <op> = <ts>` timestamp pairs in the
  logs (see `bm_instrument/ARTIFACT_EVALUATION.md` §4.4 for the exact format and a worked example).
- **mem(MB)** — not evidenced by any script in this checkout for Android; you'd need to add your
  own `adb shell dumpsys meminfo {package}` polling alongside `drive_ui.sh`.
"""


def generate_bug(bug):
    bug_dir = os.path.join(HERE, bug["id"])
    plans_dir = os.path.join(bug_dir, "plans")
    apk_dir = os.path.join(bug_dir, "apk")
    os.makedirs(plans_dir, exist_ok=True)
    os.makedirs(apk_dir, exist_ok=True)
    os.makedirs(os.path.join(bug_dir, "results"), exist_ok=True)

    dst_apk = os.path.join(apk_dir, "vector-gplay-arm64-v8a-debug.apk")
    apk_missing = not os.path.exists(dst_apk)

    notes_section = ""
    if bug.get("notes"):
        notes_section = "\n## Notes\n\n" + bug["notes"] + "\n"

    run_script = RUN_EXPERIMENT_TMPL.format(
        branch=bug["branch"], title=bug["title"], rounds=" ".join(map(str, bug["rounds"])),
        package=bug["package"], folder=bug["folder"],
    )
    run_path = os.path.join(bug_dir, "run_experiment.sh")
    with open(run_path, "w") as f:
        f.write(run_script)
    os.chmod(run_path, os.stat(run_path).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    with open(os.path.join(bug_dir, "README.md"), "w") as f:
        f.write(README_TMPL.format(
            branch=bug["branch"], title=bug["title"], element_version=bug["element_version"],
            commit=bug["commit"], package=bug["package"], symptom_class=bug["symptom_class"],
            symptom_method=bug["symptom_method"], rounds=" ".join(map(str, bug["rounds"])),
            folder=bug["folder"], notes_section=notes_section, n_rounds=len(bug["rounds"]),
        ))

    status = "MISSING APK" if apk_missing else "OK"
    print("%s: %s" % (bug["id"], status))
    return apk_missing


STUB_TMPL = """\
# Element {jira} — {title}

**Not packaged.** {reason}

See `../../bm_instrument/ARTIFACT_EVALUATION.md` §5 for the full row-by-row reproducibility map
across all 24 bugs in the results table.
"""


def generate_stub(bug):
    bug_dir = os.path.join(HERE, bug["id"])
    os.makedirs(bug_dir, exist_ok=True)
    with open(os.path.join(bug_dir, "README.md"), "w") as f:
        f.write(STUB_TMPL.format(**bug))
    print("%s: stub (not packageable)" % bug["id"])


def main():
    missing = []
    for bug in BUGS:
        if generate_bug(bug):
            missing.append(bug["id"])
    for bug in UNPACKAGEABLE:
        generate_stub(bug)
    print("\n%d bugs generated, %d with a missing APK." % (len(BUGS), len(missing)))


if __name__ == "__main__":
    main()
