#!/usr/bin/env python3
"""Materializes final_artifact/<bug-id>/ for every bug in manifest.py.

Run from anywhere; paths are resolved relative to this file. Safe to re-run (idempotent,
overwrites generated files but never touches ../bm_instrument or ../binaries source tarballs).
"""
import os
import re
import shutil
import stat
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ARTIFACTS_ROOT = os.path.dirname(HERE)  # ~/artifacts
SOURCE_BINARIES = os.path.join(ARTIFACTS_ROOT, "binaries")
SOURCE_BM_INSTRUMENT = os.path.join(ARTIFACTS_ROOT, "bm_instrument")
BINARIES_DIR = os.path.join(HERE, "binaries")

sys.path.insert(0, HERE)
from manifest import BUGS, UNPACKAGEABLE  # noqa: E402

# tarball filename each version resolves to on disk (see MISSING_ARTIFACTS.md for the ones that
# don't exist locally and must be fetched)
def tarball_name(field, value):
    if field == "cassandra_name":
        return value + "-bin.tar.gz"
    if field == "hibench_name":
        return value + ".tar.gz"
    return value + ".tar.gz"


VERSION_FIELDS = ["hadoop_name", "hbase_name", "zookeeper_name", "cassandra_name", "ycsb_name", "hibench_name"]


def injection_rounds(bug):
    """bug["rounds"] may include the "baseline" sentinel (tells run_workload.sh to also run an
    uninjected baseline pass) alongside the actual numbered instrumentation rounds. Everywhere
    that needs just the numbered rounds (README text, plans/round<N>/ counts, experimental_results
    r<N> lookups) should go through this rather than bug["rounds"] directly.
    """
    return [r for r in bug["rounds"] if r != "baseline"]

# Cluster topology: 1 master + N slaves. The real historical experimental_results/ .result
# filenames encode 4 distinct slave IPs (172.31.17.254, 172.31.18.101, 172.31.25.246,
# 172.31.26.151) — this matches that: 1 master + 3 slaves = 4 nodes total.
NUM_SLAVES = 3
SLAVE_NAMES = ["slave%d" % i for i in range(1, NUM_SLAVES + 1)]
SLAVE_HOSTS_STR = " ".join(SLAVE_NAMES)


def needed_tarballs(bug):
    out = []
    for f in VERSION_FIELDS:
        v = bug.get(f)
        if v:
            out.append((f, v, tarball_name(f, v)))
    return out


def ensure_symlink(tarball):
    src = os.path.join(SOURCE_BINARIES, tarball)
    dst = os.path.join(BINARIES_DIR, tarball)
    if os.path.islink(dst):
        # A plain symlink here would carry the absolute host path (SOURCE_BINARIES) into
        # docker-compose's `../binaries:/binaries:ro` bind mount, where that target doesn't
        # exist (only final_artifact/binaries itself is mounted) — every tarball then reads as
        # missing inside the containers. A hard link is a real directory entry for the same
        # inode, so it works no matter what's mounted, with no extra disk usage.
        os.remove(dst)
    if os.path.exists(dst):
        return os.path.exists(src)
    if os.path.exists(src):
        os.link(src, dst)
        return True
    return False


DOCKER_COMPOSE_TMPL = """\
# Auto-generated by ../generate.py from ../manifest.py — do not hand-edit, edit the manifest and
# regenerate instead. Origin command this reproduces: {origin_cmd}
services:
  master:
    build: ../common
    hostname: master
    environment: &common_env
      HADOOP_NAME: "{hadoop_name}"
      HBASE_NAME: "{hbase_name}"
      ZOOKEEPER_NAME: "{zookeeper_name}"
      CASSANDRA_NAME: "{cassandra_name}"
      YCSB_NAME: "{ycsb_name}"
      YCSB_BINDING: "{ycsb_binding}"
      YCSB_TABLE: "ycsb"
      YCSB_CF: "cf"
      HIBENCH_NAME: "{hibench_name}"
      HIBENCH_WORKLOAD: "{hibench_workload}"
      ZK_NODE_CMD: "{zk_node_cmd}"
      WORKLOAD: "{workload}"
      APP_NAME: "{app_name}"
      APP_TARGET: "{app_target}"
      NUM: "{num}"
      ROUNDS: "{rounds}"
      ENABLE_YARN: "{enable_yarn}"
      MASTER_HOST: "master"
      SLAVE_HOSTS: "{slave_hosts}"
      RESULTS_DIR: "/results"
    volumes:
      - ../binaries:/binaries:ro
      - ./plans:/plans:ro
      - ./results:/results
    networks: [bugnet]
    command: ["/opt/entrypoint.sh"]
{slave_services}
networks:
  bugnet: {{}}
"""

SLAVE_SERVICE_TMPL = """\
  {name}:
    build: ../common
    hostname: {name}
    environment:
      <<: *common_env
      ZK_MYID: "{myid}"
    volumes:
      - ../binaries:/binaries:ro
      - ./plans:/plans:ro
    networks: [bugnet]
    command: ["/opt/entrypoint.sh"]

"""


def render_slave_services():
    return "\n" + "".join(
        SLAVE_SERVICE_TMPL.format(name=name, myid=i)
        for i, name in enumerate(SLAVE_NAMES, start=1)
    )

RUN_EXPERIMENT_TMPL = """\
#!/bin/bash
# {jira} — {title}
# Auto-generated by ../generate.py from ../manifest.py.
#
# THE single command to reproduce this bug end to end:
#   ./run_experiment.sh
#
# What it does: brings up a 3-container cluster (master + slave1 + slave2) via docker compose,
# deploys the vendored {hadoop_name}{hbase_suffix}{zk_suffix}, formats/starts it, runs the
# baseline {workload_label}, then for each round in [{rounds}] injects that round's instrumentation
# plan (from ./plans/) and reruns the workload, collecting every probe's output. Results land in
# ./results/. Tears the cluster down at the end (pass --keep to leave it running for manual
# inspection, e.g. `docker compose exec master bash`).
set -euo pipefail
cd "$(dirname "$0")"

MISSING=0
{missing_check}
if [ "$MISSING" = "1" ]; then
    echo "Refusing to start: see the [MISSING] lines above. Fetch the listed file(s) into" >&2
    echo "final_artifact/binaries/ (see ../MISSING_ARTIFACTS.md), then re-run this script." >&2
    exit 42
fi

mkdir -p results
docker compose build
docker compose up -d

echo "== waiting for slaves over ssh =="
docker compose exec -T --user ubuntu master /opt/lib/wait_for_ssh.sh

echo "== preparing every node (extract vendored tarballs + render config) =="
docker compose exec -T --user ubuntu master /opt/lib/cluster_ctl.sh prepare

echo "== formatting + starting the cluster =="
docker compose exec -T --user ubuntu master /opt/lib/cluster_ctl.sh format
docker compose exec -T --user ubuntu master /opt/lib/cluster_ctl.sh start

echo "== running baseline + rounds [{rounds}] =="
docker compose exec -T --user ubuntu master /opt/lib/run_workload.sh

echo "== stopping cluster daemons =="
docker compose exec -T --user ubuntu master /opt/lib/cluster_ctl.sh stop || true

if [ "${{1:-}}" != "--keep" ]; then
    docker compose down
else
    echo "--keep passed: cluster left running. 'docker compose exec master bash' to poke around."
fi

echo "== done. Results in ./results/ =="
"""

README_TMPL = """\
# {jira} — {title}

Auto-generated by `../generate.py` from `../manifest.py` — see that file for the literal source
citation. Do not hand-edit `docker-compose.yml` / `run_experiment.sh`; edit the manifest and
regenerate (`python3 ../generate.py`).

## Reproduce

```bash
./run_experiment.sh
# results land in ./results/
```

This runs baseline, then rounds {rounds} of `./plans/round<N>/` (reorganized from the flat
`r<N>_<id>.properties` layout in `bm_instrument/{src_plans}/` into `plans/round<N>/<id>.properties`
— same layout the Android bugs use, see `final_artifact/README.md`), against the versions below.

## Versions (ground truth: `benchmark_scripts/master_*.sh`)

| Component | Version |
|---|---|
{version_rows}

**Original command this reproduces:** `{origin_cmd}`

## Instrumentation target

Workload driver: `{workload}` (see `../common/lib/run_workload.sh`). Injected process:
`{app_name}` on **{app_target}**. Symptom probe: `./plans/symptom.properties` if present (the
final, confirmed probe), else inspect the highest-numbered `./plans/round<N>/`.

{missing_section}
{notes_section}{experimental_results_section}
## Mapping to the results table

File naming (both in `results/`, from a fresh `run_experiment.sh`, and in `experimental_results/`,
the original historical run if present) matches `benchmark_scripts/*.sh` exactly: `write<name>.log`
/ `read<name>.log` for the YCSB load/run phases, `write<name>_<host>.result` /
`read<name>_<host>.result` for each host's post-phase instrumentation `collect` dump, where
`<name>` is `baseline` or `r<N>`.

- **Det?/Succ?** — check the `.result` files for the confirmed probe's value / grep the `.log`
  files for the JIRA's described symptom.
- **#Iter** = {n_rounds} (rounds {rounds}).
- **#SI** = count of `.properties` files under `./plans/round*/` (excluding `.disabled`).
- **Max%/read/write/mem/lat** — diff `write baseline.log`/`read baseline.log` against each round's
  (YCSB `-s` status lines give per-op latency you can reduce the same way as
  `bm_instrument/script_archive/parse_result.py` does). Not pre-computed here — see
  `../../bm_instrument/ARTIFACT_EVALUATION.md` §3.5 for the full caveat on this.
"""


def render_missing_check(bug):
    lines = []
    for field, value, tarball in needed_tarballs(bug):
        lines.append(
            '[ -f ../binaries/%s ] || { echo "[MISSING] binaries/%s (needed: %s=%s)" >&2; MISSING=1; }'
            % (tarball, tarball, field, value)
        )
    return "\n".join(lines) if lines else "true"


def render_readme(bug, missing, has_experimental=False):
    version_rows = []
    for field, value, tarball in needed_tarballs(bug):
        label = {
            "hadoop_name": "Hadoop", "hbase_name": "HBase", "zookeeper_name": "ZooKeeper",
            "cassandra_name": "Cassandra", "ycsb_name": "YCSB", "hibench_name": "HiBench",
        }[field]
        flag = " **[MISSING — see MISSING_ARTIFACTS.md]**" if tarball in missing else ""
        version_rows.append("| %s | `%s`%s |" % (label, value, flag))
    if bug.get("ycsb_binding"):
        version_rows.append("| YCSB binding | `%s` |" % bug["ycsb_binding"])

    missing_section = ""
    if missing:
        missing_section = (
            "## ⚠️ Missing artifacts\n\nThis bug cannot run until these are fetched into "
            "`final_artifact/binaries/` (see `../MISSING_ARTIFACTS.md`):\n\n"
            + "\n".join("- `%s`" % m for m in missing) + "\n\n"
        )

    notes_section = ""
    if bug.get("notes"):
        notes_section = "## Notes\n\n" + bug["notes"] + "\n\n"

    experimental_results_section = ""
    if bug.get("hist_root"):
        experimental_results_section = (
            "\n## Real historical run data\n\n"
            "`experimental_results/{baseline,r1,r2,...}/` holds the actual `write*.log`/`read*.log`/"
            "`*.result` files from when this bug was originally run on the real cluster (found under "
            "`~/artifacts/%s/%s_*` and copied in verbatim — filenames match exactly what a fresh "
            "`run_experiment.sh` produces, so you can diff old vs. new). Per-host raw `.class` dumps "
            "(`*_write_data/`, `*_read_data/`) were left out — debug artifacts, not measurement data. "
            "**You can compute Det?/Succ?/Max%%/read/write/mem/lat from this folder alone, with no "
            "Docker run required**, if you just need to verify the published numbers rather than "
            "reproduce the bug fresh.\n"
        ) % (bug["hist_root"], bug["hist_prefix"])
    elif has_experimental:
        experimental_results_section = (
            "\n## Legacy local logs\n\n"
            "`experimental_results/legacy_local_logs/` holds files that were sitting alongside this "
            "bug's instrumentation plans in `bm_instrument/{src_plans}/` but aren't plan files "
            "themselves (raw logs, one-off parser scripts, etc.) — preserved here rather than "
            "silently dropped during the plans/ reorganization; see that bug's own comments below "
            "for what's in there.\n"
        ).format(src_plans=bug["src_plans"])

    rounds = injection_rounds(bug)
    return README_TMPL.format(
        jira=bug["jira"], title=bug["title"], rounds=" ".join(map(str, rounds)),
        src_plans=bug["src_plans"], version_rows="\n".join(version_rows),
        origin_cmd=bug["origin_cmd"], workload=bug["workload"], app_name=bug["app_name"],
        app_target=bug["app_target"], missing_section=missing_section, notes_section=notes_section,
        experimental_results_section=experimental_results_section,
        n_rounds=len(rounds),
    )


def copy_experimental_results(bug, bug_dir):
    """Copies the real historical result dirs (write<name>.log/read<name>.log/*.result) for this
    bug's baseline + every round, found under ~/artifacts/<hist_root>/<hist_prefix>_<name>/, into
    <bug_dir>/experimental_results/<name>/. Skips the bulky per-host *_write_data/*_read_data
    subdirs (raw .class dumps of the instrumented method at attach time — debug artifacts, not
    measurement data). Returns True if anything was copied.
    """
    root = bug.get("hist_root")
    prefix = bug.get("hist_prefix")
    if not root or not prefix:
        return False
    src_root = os.path.join(ARTIFACTS_ROOT, root)
    if not os.path.isdir(src_root):
        return False

    dst_root = os.path.join(bug_dir, "experimental_results")
    if os.path.isdir(dst_root):
        shutil.rmtree(dst_root)
    copied_any = False
    for name in ["baseline"] + ["r%d" % r for r in injection_rounds(bug)]:
        src = os.path.join(src_root, "%s_%s" % (prefix, name))
        if not os.path.isdir(src):
            continue
        dst = os.path.join(dst_root, name)
        os.makedirs(dst, exist_ok=True)
        for fname in os.listdir(src):
            fpath = os.path.join(src, fname)
            if os.path.isdir(fpath):
                continue  # skip *_write_data / *_read_data per-host class dumps
            shutil.copy2(fpath, os.path.join(dst, fname))
        copied_any = True
    return copied_any


PLAN_FILENAME_RE = re.compile(r"^r(\d+)_(-?\d+)\.properties(\.disabled)?$")


def copy_plans(bug, bug_dir, has_experimental):
    """Lays out plans/ as plans/round<N>/<id>.properties[.disabled] + top-level
    plans/symptom.properties — the same layout copy_android_plans() below uses for Android bugs,
    so both tracks are structurally identical (server-side's own source layout is flat,
    r<N>_<id>.properties, with no round subdirectories — this reorganizes it on the way in).
    Anything that isn't a recognized plan file (raw logs, one-off parser scripts, etc — a handful
    of bugs' source dirs have these mixed in) is routed to experimental_results/legacy_local_logs/
    instead of being silently dropped or left cluttering plans/.
    """
    plans_dir = os.path.join(bug_dir, "plans")
    src_plans_dir = os.path.join(SOURCE_BM_INSTRUMENT, bug["src_plans"])
    if not os.path.isdir(src_plans_dir):
        print("!! %s: source plans dir missing: %s" % (bug["id"], src_plans_dir))
        return has_experimental

    legacy_dir = os.path.join(bug_dir, "experimental_results", "legacy_local_logs")
    legacy_any = False
    for fname in sorted(os.listdir(src_plans_dir)):
        src = os.path.join(src_plans_dir, fname)
        if not os.path.isfile(src):
            continue
        if fname == "symptom.properties":
            shutil.copy2(src, os.path.join(plans_dir, "symptom.properties"))
            continue
        m = PLAN_FILENAME_RE.match(fname)
        if m:
            round_num, plan_id, disabled = m.groups()
            round_dir = os.path.join(plans_dir, "round%s" % round_num)
            os.makedirs(round_dir, exist_ok=True)
            new_name = "%s.properties%s" % (plan_id, disabled or "")
            shutil.copy2(src, os.path.join(round_dir, new_name))
            continue
        # not a plan file (raw log, parser script, notes, ...) — preserve it as provenance
        os.makedirs(legacy_dir, exist_ok=True)
        shutil.copy2(src, os.path.join(legacy_dir, fname))
        legacy_any = True
    return has_experimental or legacy_any


def generate_bug(bug):
    bug_dir = os.path.join(HERE, bug["id"])
    plans_dir = os.path.join(bug_dir, "plans")
    if os.path.isdir(plans_dir):
        shutil.rmtree(plans_dir)  # avoid stale leftovers from a previous layout across reruns
    os.makedirs(plans_dir, exist_ok=True)
    os.makedirs(os.path.join(bug_dir, "results"), exist_ok=True)
    has_experimental = copy_experimental_results(bug, bug_dir)
    has_experimental = copy_plans(bug, bug_dir, has_experimental)

    missing = []
    os.makedirs(BINARIES_DIR, exist_ok=True)
    for field, value, tarball in needed_tarballs(bug):
        if not ensure_symlink(tarball):
            missing.append(tarball)

    compose = DOCKER_COMPOSE_TMPL.format(
        origin_cmd=bug["origin_cmd"],
        hadoop_name=bug.get("hadoop_name", ""), hbase_name=bug.get("hbase_name", ""),
        zookeeper_name=bug.get("zookeeper_name", ""), cassandra_name=bug.get("cassandra_name", ""),
        ycsb_name=bug.get("ycsb_name", ""), ycsb_binding=bug.get("ycsb_binding", ""),
        hibench_name=bug.get("hibench_name", ""), hibench_workload=bug.get("hibench_workload", ""),
        zk_node_cmd=bug.get("zk_node_cmd", ""), workload=bug["workload"], app_name=bug["app_name"],
        app_target=bug["app_target"], num=bug["num"], rounds=" ".join(map(str, bug["rounds"])),
        enable_yarn="1" if bug.get("enable_yarn") else "0",
        slave_hosts=SLAVE_HOSTS_STR, slave_services=render_slave_services(),
    )
    with open(os.path.join(bug_dir, "docker-compose.yml"), "w") as f:
        f.write(compose)

    hbase_suffix = " + %s" % bug["hbase_name"] if bug.get("hbase_name") else ""
    zk_suffix = " + %s" % bug["zookeeper_name"] if bug.get("zookeeper_name") else ""
    workload_label = {
        "ycsb_hbase": "YCSB-vs-HBase workload", "ycsb_hbase_old": "YCSB-vs-HBase (legacy) workload",
        "ycsb_zk": "YCSB-vs-ZooKeeper workload", "ycsb_cass": "YCSB-vs-Cassandra workload",
        "hibench": "HiBench terasort+pagerank workload",
    }[bug["workload"]]
    run_script = RUN_EXPERIMENT_TMPL.format(
        jira=bug["jira"], title=bug["title"], hadoop_name=bug.get("hadoop_name", ""),
        hbase_suffix=hbase_suffix, zk_suffix=zk_suffix, workload_label=workload_label,
        rounds=" ".join(map(str, injection_rounds(bug))), missing_check=render_missing_check(bug),
    )
    run_path = os.path.join(bug_dir, "run_experiment.sh")
    with open(run_path, "w") as f:
        f.write(run_script)
    os.chmod(run_path, os.stat(run_path).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    with open(os.path.join(bug_dir, "README.md"), "w") as f:
        f.write(render_readme(bug, missing, has_experimental))

    print("%s: %s%s%s" % (bug["id"], "OK" if not missing else "MISSING " + ",".join(missing),
                           "" if not missing else " <-- flagged",
                           " [+experimental_results]" if has_experimental else ""))
    return missing


STUB_TMPL = """\
# {jira} — {title}

**Not packaged.** {reason}

This artifact only packages bugs that have a `server-bugs/instrumentation_*` folder in
`bm_instrument` — see `../../bm_instrument/ARTIFACT_EVALUATION.md` §5 for the full row-by-row
reproducibility map across all 24 bugs in the results table (13 packageable server-side bugs +
5 packageable Android bugs + this one and 3 others that aren't).
"""


def generate_stub(bug):
    bug_dir = os.path.join(HERE, bug["id"])
    os.makedirs(bug_dir, exist_ok=True)
    with open(os.path.join(bug_dir, "README.md"), "w") as f:
        f.write(STUB_TMPL.format(**bug))
    print("%s: stub (not packageable)" % bug["id"])


def main():
    all_missing = {}
    for bug in BUGS:
        m = generate_bug(bug)
        if m:
            all_missing[bug["id"]] = m
    for bug in UNPACKAGEABLE:
        generate_stub(bug)
    print("\n%d bugs generated, %d with missing artifacts." % (len(BUGS), len(all_missing)))
    return all_missing


if __name__ == "__main__":
    main()
